pipeline {
  agent { 
    dockerfile {
        filename 'Dockerfile'
        dir 'M2-jenkins-with-zap'
        args '-u root'
    }
  }
  stage('tfsec') {
    agent {
        docker { 
            image 'tfsec/tfsec-ci:v0.57.1' 
            reuseNode true
        }
    }
    steps {
    sh '''
        tfsec . --no-color
    '''
    }
  }
  stages {
    stage('Test') {
      steps {
        sh '''
          zap-baseline.py -t http://demo.testfire.net
        '''
      }
    }
  }
}