pipeline {
  agent { 
    dockerfile {
        filename 'Dockerfile'
        dir 'M2-jenkins-with-zap'
        args '-u zap'
    }
  }
  stages {
    stage('Test') {
      steps {
        sh '''
          zap-baseline.py -t http://demo.testfire.net
        '''
      }
    }
  }
}